kind: pipeline
name: unfederal
steps:

- name: build
  image: node:12.19.1
  volumes:
  - name: build_dest
    path: /dest
  commands:
  - yarn install
  - yarn build
  - rm -rf /dest/*
  - cp -r build/* /dest/

- name: notify-slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slackwebhook
    channel: unfederalreserve
    username: drone.io-bot
    icon_url: https://xebialabs.com/wp-content/uploads/2018/10/droneio-1.jpg
    template: >
     {{#if build.pull }}
        *{{#success build.status}}✔{{ else }}✘{{/success}} <{{ build.link }}|{{ uppercasefirst build.status }}>*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
     {{else}}
        *{{#success build.status}}✔{{ else }}✘{{/success}} <{{ build.link }}|{{ uppercasefirst build.status }}: Build #{{ build.number }}>*
     {{/if}}
     {{ build.author }} -> <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> -> <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ repo.name }}/{{ build.branch }}>: _"${DRONE_COMMIT_MESSAGE}"_
  when:
    status: [ success, failure ]

trigger:
  branch:
  - master
  - dev
  event:
  - push

volumes:
- name: build_dest
  host:
    path: /storage/${DRONE_COMMIT_BRANCH}/unfederal
